### ISSUE TITLE
List members

### ISSUE THREAD

**Issue by Sabramz** [Oasis-NEU/f23-group06#1]
Campbell's got this one

**Comment by Sabramz** [comment]
@Spylee01 Use the materialUI <DataGrid> when you are making the table component. Here are the docs for a table: https://mui.com/material-ui/react-table/

**Comment by russell-leung** [comment]
@Spylee01 @Sabramz  I'm going to create a branch for this and move the add members modal into a new page /club/members/add this page should have the table w a button to navigate to add members

**Comment by russell-leung** [comment]
Branch: #1-list-members

**Comment by Sabramz** [comment]
@Spylee01 Actually use NextUI's table. NextUI OP.
https://nextui.org/docs/components/table
